enum StorageKeys {
    static let appearanceMode = "appearanceMode"
    static let adhkarContentRevision = "adhkarContentRevision"
    static let prayerLatitude = "prayerLatitude"
    static let prayerLongitude = "prayerLongitude"
    static let prayerTimeZone = "prayerTimeZone"
    static let prayerCity = "prayerCity"
    static let calculationMethod = "calculationMethod"
    static let asrMadhab = "asrMadhab"
    static let highLatitudeRule = "highLatitudeRule"
    static let lastReadSurah = "lastReadSurah"
    static let quranLastRead = "quranLastRead.v1"
    static let quranBookmarks = "quranBookmarks.v1"
    static let quranKhatmah = "quranKhatmah.v1"
    static let prayerRemindersEnabled = "prayerRemindersEnabled"
    static let tasbihCount = "tasbihCount"
    static let tasbihTarget = "tasbihTarget"
    static let fridaySunnahPrefix = "fridaySunnah."
}
